Feat/Added Blog Page Layout
stevensblueprint/blueprint_website pull request #208
Opened 2024-10-15 02:06 UTC by zClerigo

![Screenshot 2024-10-14 at 21-58-11 Stevens Blueprint Blog](https://github.com/user-attachments/assets/bfa7d227-4d83-4ab8-b882-c0a0b027c656)

- This layout does not interact with the files in the blog folder
- Screenshot displays the page when the code in blog.md is uncommented.
- Blog page currently displays placeholder layout

2024-10-15 02:08 UTC, zClerigo commented
I am not sure why blog.md is failing prettier check.

2024-10-15 17:26 UTC, Caposto commented
@zClerigo Looking good so far! In regards to the blog failing prettier, what happens when you run `npm run prettier --format`?

2024-10-15 17:30 UTC, Caposto commented on src/assets/vector/clock.png
Is there a .svg version of the clock? Not a huge deal, but svg files are typically smaller and can scale well without blurring

2024-10-15 18:10 UTC, zClerigo commented on src/assets/vector/clock.png
Hi, Caposto. Running `npm run prettier:write` results in the blog.md file being formatted smoothly.

I also replaced the .png with a .svg clock. I will close this pull request and make a new one promptly.

2024-10-15 22:44 UTC, Caposto requested changes
- For the svgs for filter topics add them to the assets folder as well
- Adjust padding to fill more of the page
- Add 3 more example blogs

2024-10-15 22:44 UTC, Caposto commented on src/blog.md
Prettier might be failing due to the extra space at the bottom, but lmk what happens when you run `npm run format:write`

2024-10-15 22:44 UTC, Caposto commented on src/_includes/_layouts/Blog.jsx
Great work so far! I know you're still working, but noticed there's a bit of padding on the left and right sizes. I think in the designs we might want to be a little closer to the edges:

![image](https://github.com/user-attachments/assets/54044e8f-150f-4e5a-86c6-b10d51933d0a)

I think running throgh and adjusting some of the mx-*, mb-*, p-* could do the trick cc @ShawnAviles

2024-10-16 04:30 UTC, ShawnAviles requested changes
Left comment about the large white space on the left and right but overall nice job! Love how similar you got it to the designs 🫡

2024-10-16 04:30 UTC, ShawnAviles commented on src/_includes/_layouts/Blog.jsx
>        <main className="max-w-4xl mx-auto p-4">
Adding onto Christian's comment about the padding on the left and right, here the width is being maxxed out at `max-w-4xl` but that is what's restricting the layout to have such large left and right padding. 

You can change it be something like `max-w-6xl` to reduce the large horizontal space but other things would have to increase in size too to accommodate the white space

2024-10-17 23:16 UTC, zClerigo commented
![Screenshot 2024-10-17 at 19-14-13 Stevens Blueprint Blog](https://github.com/user-attachments/assets/827f0266-2780-40f8-ba28-4b42fb4ca4b0)
New changes pushed

2024-10-17 23:33 UTC, ShawnAviles submitted a review, later dismissed
Nice job, LGTM 👍 

NIT: Just so we know, it would be helpful to have a comment there stating that "Uncomment this to show mock blog posts" so that we can remember incase this PR gets lost or someone without context were to try to view it.

2024-10-18 20:38 UTC, Caposto approved these changes

2024-10-18 20:39 UTC, merged