Feat/npo hero
stevensblueprint/blueprint_website pull request #224
Opened 2024-11-03 03:56 UTC by Caposto

# Description 
Related to issue #222 

![image](https://github.com/user-attachments/assets/5212b073-2a24-4dd3-a704-3d590548cde5)

Implemented responsiveness, but **NO MOBILE IMPLEMENTATION**

Also, please see folder structure for this PR. I think making each page section into its own component will help with future maintainability. If you review this please leave your thoughts if you think we should apply this to every other page or if its unecessary refactoring.

2024-11-06 13:48 UTC, ShawnAviles requested changes
Requested some changes. Overall nice job 👍 

I do like the refactor to having page specific components grouped in their own folder. we can implement that now moving forward

2024-11-06 13:48 UTC, ShawnAviles commented on src/_components/ForNPOs/Hero.jsx
> +          <br />
Instead of implementing direct line breaks. You should try to have the overall container have the appropriate padding on the left and right to look as similar to the design as possible. 

Otherwise, it looks its responsiveness and can be funky at different sizes (see below):

<img width="609" alt="Screenshot 2024-11-05 at 8 07 49 PM" src="https://github.com/user-attachments/assets/056d9b6a-e61b-4a3e-b2ed-426385e0b713">

2024-11-06 13:48 UTC, ShawnAviles commented on src/_components/ForNPOs/Hero.jsx
> +          <comp.Button
I think these button need a hover effect where they turn white and the text turns blue - according to the figma

2024-11-06 13:48 UTC, ShawnAviles commented on src/_components/ForNPOs/Hero.jsx
> +      <img
You should nest the image in its own div and center that using flex box something like `flex px-6 md:px-12 lg:32 grow w-full justify-center pb-12` 

**Note**: I recommend using `w-full` on this div and the parent div of the left side so that both divs attempt to take up 100% of the width and they end up splitting it evenly.

2024-11-06 13:48 UTC, ShawnAviles commented on src/_components/ForNPOs/Hero.jsx
> +        className="hidden lg:block transform -translate-y-10 lg:translate-x-20 xl:translate-x-80"
we can remove all of the classes applied directly to the image since we can handle it with the outer div centering (also easier to handle horizontal padding and making it consistent with the left side content)

2024-11-06 13:48 UTC, ShawnAviles commented on src/_components/ForNPOs/Hero.jsx
> +            style="h-10 px-6 md:px-8 min-w-[191px] rounded-md border border-white justify-center items-center gap-2 text-white font-semibold text-base md:text-lg inline-flex"
I believe hard setting `h-10` causes a slight issue with resizing so if the page shrinks to a certain breakpoint it causes the text to overflow out of the button (see image below). You could fix that by not setting the height but adding `py-2` so the button just has a consistent vertical padding too. Additionally, if you want the next itself to be centered in this weird state, you can apply `text-center` div too (the flex centering only centers the text container not aligns the text itself)

<img width="300" alt="Screenshot 2024-11-06 at 8 45 01 AM" src="https://github.com/user-attachments/assets/6742d4b2-6a85-4c0a-8f0c-7df84856c0a8">

2024-11-06 13:48 UTC, ShawnAviles commented on src/_components/ForNPOs/Hero.jsx
> +            style="h-10 px-6 md:px-8 min-w-[191px] rounded-md border border-white justify-center items-center gap-2 text-white font-semibold text-base md:text-lg inline-flex"
same button comment as above applies here

2024-11-06 23:22 UTC, co16661666 approved these changes

2024-11-07 03:49 UTC, ShawnAviles approved these changes
Nice. LGTM 👍

2024-11-07 03:50 UTC, merged