Resolved #21, #20, #18, #17
stevensblueprint/blueprint_website pull request #30
Opened 2023-11-03 22:16 UTC by ZhangTerrence

2023-11-03 22:18 UTC, ericzty requested changes

2023-11-03 22:18 UTC, ericzty commented on src/assets/logos/stevens_logo.svg
Let's not use the Stevens logo since we have to clear that with Stevens Admins first.

2023-11-03 22:41 UTC, ericzty approved these changes
looks good to me, nice work.

2023-11-05 18:58 UTC, miguel-merlin approved these changes

2023-11-05 18:58 UTC, merged